version: '3.3'
services:
  fluentd:
    build: ./fluentd
    restart: always
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - $PWD/log/:/kernelci/log/:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2 
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    volumes:
      - es:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2 
    ports:
      - 5601:5601
    restart: always
volumes:
  es:
